// Mocks generated by Mockito 5.4.6 from annotations
// in clothing_store/test/feature/auth/data/repository/auth_repo_impl_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i3;

import 'package:clothing_store/core/error/result.dart' as _i4;
import 'package:clothing_store/feature/auth/data/datasourse/remote_data_sourse.dart'
    as _i2;
import 'package:clothing_store/feature/auth/data/models/sign_up_model.dart'
    as _i7;
import 'package:firebase_auth/firebase_auth.dart' as _i5;
import 'package:mockito/mockito.dart' as _i1;
import 'package:mockito/src/dummies.dart' as _i6;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class
// ignore_for_file: invalid_use_of_internal_member

/// A class which mocks [RemoteDataSourse].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoteDataSourse extends _i1.Mock implements _i2.RemoteDataSourse {
  MockRemoteDataSourse() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i3.Future<_i4.Result<_i5.User>> signInWithEmailAndPassowrd(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#signInWithEmailAndPassowrd, [email, password]),
            returnValue: _i3.Future<_i4.Result<_i5.User>>.value(
              _i6.dummyValue<_i4.Result<_i5.User>>(
                this,
                Invocation.method(#signInWithEmailAndPassowrd, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.User>>);

  @override
  _i3.Future<_i4.Result<_i5.UserCredential>> signInWithGoogle() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithGoogle, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserCredential>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserCredential>>(
                this,
                Invocation.method(#signInWithGoogle, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserCredential>>);

  @override
  _i3.Future<_i4.Result<_i5.UserCredential>> signInWithFacebook() =>
      (super.noSuchMethod(
            Invocation.method(#signInWithFacebook, []),
            returnValue: _i3.Future<_i4.Result<_i5.UserCredential>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserCredential>>(
                this,
                Invocation.method(#signInWithFacebook, []),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserCredential>>);

  @override
  _i3.Future<_i4.Result<void>?> signUp(_i7.SignUpModel? signUpModel) =>
      (super.noSuchMethod(
            Invocation.method(#signUp, [signUpModel]),
            returnValue: _i3.Future<_i4.Result<void>?>.value(),
          )
          as _i3.Future<_i4.Result<void>?>);

  @override
  _i3.Future<_i4.Result<_i5.UserCredential>> createUserWithEmailAndPassword(
    String? email,
    String? password,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#createUserWithEmailAndPassword, [
              email,
              password,
            ]),
            returnValue: _i3.Future<_i4.Result<_i5.UserCredential>>.value(
              _i6.dummyValue<_i4.Result<_i5.UserCredential>>(
                this,
                Invocation.method(#createUserWithEmailAndPassword, [
                  email,
                  password,
                ]),
              ),
            ),
          )
          as _i3.Future<_i4.Result<_i5.UserCredential>>);

  @override
  _i3.Future<_i4.Result<void>?> resetPassword(String? email) =>
      (super.noSuchMethod(
            Invocation.method(#resetPassword, [email]),
            returnValue: _i3.Future<_i4.Result<void>?>.value(),
          )
          as _i3.Future<_i4.Result<void>?>);
}
